export default [
    {
        name:'首页',
        children:[
            {
                name:'后台管理',
                icon:"el-icon-s-home",
                url:'/index'
            }, 
            {
                name:'相册管理',
                icon:"el-icon-picture",
                url:'/picture'
            },
            {
                name:'用户列表',
                icon:"el-icon-s-cooperation",
                url:'/index'
            },
        ]
    },
    {
        name:'商品',
        children:[
            {
                name:'商品列表',
                icon:"el-icon-s-data",
                url:'/goodlist'
            }, 
            {
                name:'分类列表',
                icon:"el-icon-s-data",
                url:'/index'
            },
            {
                name:'商品规格',
                icon:"el-icon-s-data",
                url:'/index'
            },
            {
                name:'商品价格',
                icon:"el-icon-s-data",
                url:'/index'
            },
            {
                name:'商品分类',
                icon:"el-icon-s-data",
                url:'/index'
            },
        ]
    },
    {
        name:'订单',
        children:[
            {
                name:'订单管理',
                icon:"el-icon-s-order",
                url:'/index'
            }, 
            {
                name:'发票管理',
                icon:"el-icon-s-order",
                url:'/index'
            },
        ]
    },
    {
        name:'会员',
        children:[
            {
                name:'会员列表',
                icon:"el-icon-s-custom",
                url:'/list'
            }, 
            {
                name:'会员等级',
                icon:"el-icon-s-check",
                url:'/index'
            },
        ]
    },
    {
        name:'设置',
        children:[
            {
                name:'基础设置',
                icon:"el-icon-s-help",
                url:'/setting'
            },
        ]
    }
]